apiVersion: skaffold/v2alpha3
kind: Config
deploy:
    kubectl:
        manifests:
            - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
      - image: joseluisjb1990/tickets
        context: tickets
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: joseluisjb1990/payments
        context: payments
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: joseluisjb1990/orders
        context: orders
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: joseluisjb1990/expiration
        context: expiration
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: joseluisjb1990/auth
        context: auth
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
              - src: 'src/**/*.ts'
                dest: .
      - image: joseluisjb1990/client
        context: client
        docker:
          dockerfile: Dockerfile
        sync:
          manual:
            - src: '**/*.js'
              dest: .