name: tests-orders
on:
  pull_request:
    paths:
      - 'orders/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd orders && npm install --no-package-lock && npm run test:ci
     
